Controllers films users
ARGalimov/java-filmorate pull request #3
Opened 2023-05-11 18:39 UTC by ARGalimov

Выполнено ТЗ ФЗ9

2023-05-12 21:48 UTC, Yang-Pi requested changes

2023-05-12 21:48 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserValidator.java
> +public class UserValidator {
Если честно, то не очень согласен с такой реализацией валидации. На самом деле у тебя одинаковые проверки для post и put запросов, те можно сделать один метод validate прямо в рамках контролера.

2023-05-13 09:54 UTC, ARGalimov commented on .gitignore
> -*.log
Даааа, я зачем-то добавил лишние файлы в отслеживаемые, потом убирал... Этот файл тоже надо убрать или пусть уже болтается в этой ветке?

2023-05-14 07:56 UTC, ARGalimov commented on .gitignore
> -*.log
Убрал файл

2023-05-14 07:56 UTC, ARGalimov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Я думал, что тестов по JSON файлу из ТЗ достаточно. Дописал тесты валидации

2023-05-14 07:56 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserValidator.java
> +public class UserValidator {
Перенес валидацию в контроллер

2023-05-15 06:02 UTC, Yang-Pi requested changes

2023-05-15 06:02 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public static void validateUser(User user) throws ValidationException {
А для чего ты решил сделать методы валидации а) публичными б) статическими?
Они используются только в рамках объекта контроллера, поэтому должны быть приватными и не статическими (в общем, наоборот все).

2023-05-15 14:39 UTC, ARGalimov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Убрал этот класс

2023-05-15 14:56 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {
Поправил

2023-05-16 06:12 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String description;
признаюсь честно, у меня не получилось выполнить задание со звездочкой, так и не победил выполнение валидации по модели. Поэтому из модели убрал проверки и выполнил в отдельном классе ValidateTest

2023-05-16 06:12 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public static void validateUser(User user) throws ValidationException {
Переделал на приватные и не статические

2023-05-16 06:37 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
Добавил проверку

2023-05-16 15:13 UTC, Yang-Pi requested changes

2023-05-16 15:13 UTC, Yang-Pi commented on .github/workflows/api-tests.yml
Вот этот файл и остальные, относящиеся с CI программы, не нужно менять и удалять, поэтому верни их, пожалуйста.

2023-05-16 15:13 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription() != null & film.getDescription().length() > 200) {
Только нужно использовать не побитовый оператор &, а логический оператор &&

2023-05-16 15:13 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {
Не вижу(

2023-05-16 15:13 UTC, Yang-Pi commented on src/test/java/ru/yandex/practicum/filmorate/controller/ValidateTest.java
> +    void testFilmNameIsBlankOrNull() {
Лучше раздели этот тестовый класс на два - про фильмы и про юзеров.

2023-05-16 17:15 UTC, ARGalimov commented on .github/workflows/api-tests.yml
пометил как отслеживаемый

2023-05-16 17:15 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getLogin() == null || user.getLogin().isBlank() || user.getLogin().contains(" ")) {
поправил. В прошлой итерации поправил в другом классе аналогичную ошибку ))

2023-05-16 17:17 UTC, ARGalimov commented on src/test/java/ru/yandex/practicum/filmorate/controller/ValidateTest.java
> +    void testFilmNameIsBlankOrNull() {
разделил

2023-05-17 17:22 UTC, Yang-Pi approved these changes

2023-05-21 18:00 UTC, merged