add-friends-likes выполнить ФЗ 10
ARGalimov/java-filmorate pull request #4
Opened 2023-05-26 17:32 UTC by ARGalimov

2023-05-27 11:17 UTC, Yang-Pi requested changes

2023-05-27 11:17 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoDataException.java
> +public class NoDataException extends Exception {
Для своих исключений лучше наследовать от RuntimeException, это проверяемое исключение, которое мы точно хотим как-то обработать.

2023-05-27 11:17 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        validateFilmUpdate(films, film);
Чтобы вот так не писать подряд два метода, то вызов validateFilm можешь внести в метод validateFilmUpdate

2023-05-27 11:17 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<Integer> commonFriends = userStorage.getUserList()
Такой длинный стрим не самый удобный для восприятия, лучше такой алгоритм писать в виде циклов

2023-05-27 17:08 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        validateFilmUpdate(films, film);
Поправил

2023-05-27 17:11 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        return new ErrorResponse("Ошибка", e.getMessage());
Добавил логирование

2023-05-27 17:16 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Добавил

2023-05-27 17:17 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/exception/NoDataException.java
> +public class NoDataException extends Exception {
поправил

2023-05-27 17:49 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<Integer> commonFriends = userStorage.getUserList()
Переписал на цикл

2023-05-28 08:56 UTC, Yang-Pi reviewed
Падают проверки кода

2023-05-28 18:56 UTC, Yang-Pi approved these changes

2023-05-31 17:38 UTC, merged