add-database выполнить ТЗ
ARGalimov/java-filmorate pull request #5
Opened 2023-06-20 20:26 UTC by ARGalimov

2023-06-21 20:44 UTC, Yang-Pi requested changes

2023-06-21 20:44 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@RequestMapping("/films")
Зря ты убрал, более удачным решением было бы сделать отдельный контролер для жанров и рейтинга.

2023-06-21 20:44 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Qualifier("filmDbStorage") FilmStorage filmStorage) {
Только переименуй qualifier у самого хранилища - первая буква там заглавная

2023-06-21 20:44 UTC, Yang-Pi commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                        "LEFT JOIN GENRE AS g ON g.ID = f.ID_GENRE" +
А почему используешь Left Join - так ты выведешь все жанры, а не конкретно жанры фильма. Нужно использовать Inner Join (или просто join)

2023-06-22 03:27 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Qualifier("filmDbStorage") FilmStorage filmStorage) {
Исправил

2023-06-22 03:28 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                        "LEFT JOIN GENRE AS g ON g.ID = f.ID_GENRE" +
Исправил

2023-06-22 04:22 UTC, ARGalimov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@RequestMapping("/films")
разделил на разные контролеры

2023-06-23 07:54 UTC, Yang-Pi approved these changes

2023-06-24 18:22 UTC, merged